services:
  - type: web
    name: telegram-monitor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_API_ID
        sync: false
      - key: TELEGRAM_API_HASH
        sync: false
      - key: TELEGRAM_PHONE
        sync: false
      - key: TELEGRAM_SESSION
        sync: false
      - key: TARGET_CHANNEL
        value: Sport_433et
      - key: COMMENT_MESSAGES
        value: hey this is me